# Generated by Django 5.2 on 2025-04-15 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('lol', 'League of Legends'), ('marvel', 'Marvel Rivals'), ('valorant', 'Valorant'), ('overwatch', 'Overwatch'), ('apex', 'Apex Legends')], max_length=50)),
                ('rank', models.CharField(max_length=100)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bio', models.TextField()),
                ('availability', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
