# Generated by Django 5.2 on 2025-04-15 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring_Website', '0002_coachprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='game',
            field=models.CharField(choices=[('lol', 'League of Legends'), ('marvel', 'Marvel Rivals'), ('valorant', 'Valorant'), ('overwatch', 'Overwatch'), ('fortnite', 'Fortnite'), ('rocketleague', 'Rocket League'), ('smash', 'Super Smash Bros'), ('pokemon', 'Pokemon TCG')], max_length=50),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('message', models.TextField()),
                ('discord_id', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutoring_Website.coachprofile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
