# Generated by Django 5.2 on 2025-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutoring_Website', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
